name: Python Test Scoring

on:
  push:
    branches: [ "main", "yololab" ]
  pull_request:
    branches: [ "main", "yololab" ]

jobs:
  test:
    if: github.repository_owner != 'PythonTrainingCamp'
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      PIP_CACHE_DIR: $RUNNER_TEMP/pip-cache

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Update apt sources
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:graphics-drivers/ppa
          sudo apt update

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-get update
          sudo apt-get install -y libgl1
          pip install -r requirements.txt

      - name: Debug environment
        run: |
          echo "当前工作目录:"
          pwd
          echo "目录内容:"
          ls -la
          echo "Python版本:"
          python --version
          echo "安装的包:"
          pip list
          echo "PYTHONPATH: $PYTHONPATH"
          echo "RUNNER_TEMP: $RUNNER_TEMP"

      - name: Run pytest tests
        continue-on-error: true
        run: |
          python -m pytest tests/ -v --junitxml=test-results.xml

      - name: Run score calculator
        run: |
          python score_calculator.py

      - name: Print test results score
        run: |
          echo "测试分数报告:"
          cat test_score.txt
          echo "### 测试分数" >> $GITHUB_STEP_SUMMARY
          cat test_score.txt >> $GITHUB_STEP_SUMMARY

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            test_score.txt
            test-results.xml