name: Python Test Scoring

on:
  push:
    branches: [ "main", "yololab" ]
  pull_request:
    branches: [ "main", "yololab" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opencv-python>=4.5.0 numpy>=1.21.0 pytest>=6.0.0

    - name: Run score calculator
      run: |
        # 设置PYTHONPATH以确保能够找到exercises模块
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python score_calculator.py
      
    - name: Print test results
      run: |
        cat test_score.txt

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test_score.txt
