name: Python Test Scoring

on:
  push:
    branches: [ "main", "yololab" ]
  pull_request:
    branches: [ "main", "yololab" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 安装OpenCV的系统依赖
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx
        # 安装Python依赖
        pip install opencv-python>=4.5.0 numpy>=1.21.0 pytest>=6.0.0

    - name: Debug environment
      run: |
        echo "当前工作目录:"
        pwd
        echo "目录内容:"
        ls -la
        echo "Python版本:"
        python --version
        echo "安装的包:"
        pip list

    - name: Run pytest tests
      run: |
        # 设置PYTHONPATH以确保能够找到exercises模块
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python -m pytest tests/ -v --junitxml=test-results.xml

    - name: Run score calculator
      run: |
        # 设置PYTHONPATH以确保能够找到exercises模块
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python score_calculator.py
      
    - name: Print test results with progress bar
      run: |
        cat test_score.txt
        echo ""
        echo "测试进度可视化："
        PROGRESS=$(grep "Progress" test_score.txt | cut -d' ' -f2)
        echo $PROGRESS

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: |
          test_score.txt
          test-results.xml
